### PR TITLE
Added support to MongoDb Atlas + general improvements

### PR DESCRIPTION
**Pull request by informagico**
## Changelog

- Added **optional** support to MongoDB Atlas to store performed orders results (for further analysis).
  Collection/Documents structure is as per [New Order (TRADE) FULL Response Binance API documentation](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade).
- Made completely optional the config.js file (just needed to be there to simplify some logic, it can be removed with some additional work).
  Everything can now be fetched from Environment Variables (process.env.xxx), config.js file or a mix of the two.
- Added more controls over config/env data in order to avoid unwanted behaviors.
- Minor improvements.

**PS:** this is of course based on PR #9 and contains all those features.

### CODE REVIEW

**Review by lukeliasi — COMMENTED** [review]
I don't think config.js needs to be committed and removed from .gitignore. Having this may lead to someone accidently committing their secret keys. I think the file can just be copied from example template?

**Comment by dakkusingh** [comment]
Any chance we can get this merged?

**Comment by lukeliasi** [comment]
> Yeah, I understand. I have added config.js just to facilitate CD on any git-based SaaS. My idea was to completely drop the config.js and go full with process.env variables but I completely understand that this is a breaking change.
> 
> I think I'll go with:
> 
> * Restore the .gitignore
> * Remove the config.js
> * Make another branch with dropped support for config.js so anyone can choose what to use
> 
> Unfortunately I don't have much time to think about something simpler.

Ah yes makes sense regarding SaaS where you deploy via git and have no control over file system. How about to make this simple we store the config of what buys you want to execute in **config.js** e.g:

config.js:
`export const config = [
    {
      asset: "BTC", // Asset you want to buy
      currency: "GBP", // Currency you want to buy the asset with
      quoteOrderQty: 10, // Buy £10 GBP worth of BTC
      schedule: "0 4 * * SUN"  // Place order every Sunday at 4am - https://crontab.guru/#0_4_*_*_SUN
    },
    {
      asset: "LSK",
      currency: "BTC", // Buy LSK with BTC
      quantity: 5, // Buy 5 LSK, regardless of the price
      schedule: "0 22 * * 1-5"  // Place order on the first day of every month - https://crontab.guru/#0_0_1_*_*
    },
]`

And we remove it from .gitignore and commit it. It may even make sense to possibly rename config.js to something like trades.js just so it's clear.

Then everything else, keys, secrets and other config options can be defined in .env/environment variables? This change can bump the project to v2.0.0 indicating a major/breaking change.

**Comment by informagico** [comment]
@lukeliasi @dakkusingh please refer to PR #18 for further updates on this topic. I finally had some time to work on this.

**Pull request closed without merging**
